### ISSUE TITLE
Handle Invitations of existing Users to a Company [1Jan2018-1005]

### ISSUE THREAD

**Issue by jinnerbichler** [nimble-platform/identity-service#20]
Currently, it is not possible to invited users, which are already on the platform.

**Comment by jinnerbichler** [comment]
This would result in a state, where one user is part of multiple companies, which is not yet supported.

**Comment by wernher** [comment]
The issue is that a user may be registered, but not yet associated to any company. If that user is invited even for the first time, to just one company, then this does not work at present.

**Comment by jinnerbichler** [comment]
For now, just inform the inviting party that the invitee is already associated with another company.

**Comment by jinnerbichler** [comment]
Multiple companies associated with a single user is targeted by issue #28
