### ISSUE TITLE
Pass postgress details in environment variable

### ISSUE THREAD

**Issue by pashok2398** [nimble-platform/identity-service#6]
The tomcat service trying to access localhost:5433 with some default username and password.
Please add option to start the identity-service with 
```
--env POSTGESS_USER=some_user \
--env POSTGRES_SPASSWORD=some_password \
--env POSTGRESS_HOST=some_host \
--env POSTGRESS_PORT=some_port 
```
The current option is problematic with kubernetes deployment as both identity-service and postgress must be in the same pod and there is no sequential start option so the identity-service container start before postgress container is ready and failed.

**Comment by jinnerbichler** [comment]
Hello @pashok2398,
can you checkout the current master #and check if the appropriate configuration capabilities are implemented?

The corresponding configuration can be bound in `identity-service/src/main/resources/bootstrap.yml`.

`  
datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:${POSTGRES_PORT:5432}}/${POSTGRES_DB:identityDB}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:changeme}
`

**Comment by bienstock** [comment]
Now the mvn build fails with the following error:

[INFO] writing file /home/gadm/workspace/identity-service/identity-service/target/generated-sources/swagger/index.html
[INFO] writing file /home/gadm/workspace/identity-service/identity-service/target/generated-sources/swagger/LICENSE
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ identity-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ identity-service ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 32 source files to /home/gadm/workspace/identity-service/identity-service/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /home/gadm/workspace/identity-service/identity-service/src/main/java/eu/nimble/core/infrastructure/identity/utils/UblUtils.java: /home/gadm/workspace/identity-service/identity-service/src/main/java/eu/nimble/core/infrastructure/identity/utils/UblUtils.java uses unchecked or unsafe operations.
[WARNING] /home/gadm/workspace/identity-service/identity-service/src/main/java/eu/nimble/core/infrastructure/identity/utils/UblUtils.java: Recompile with -Xlint:unchecked for details.
[INFO] 2 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/gadm/workspace/identity-service/identity-service/src/main/java/eu/nimble/core/infrastructure/identity/utils/UblAdapter.java:[20,35] cannot find symbol
  symbol:   method getName()
  location: variable partyType of type eu.nimble.service.model.ubl.commonaggregatecomponents.PartyType
[ERROR] /home/gadm/workspace/identity-service/identity-service/src/main/java/eu/nimble/core/infrastructure/identity/utils/UblAdapter.java:[129,48] cannot find symbol
  symbol:   method getName()
  location: variable company of type eu.nimble.service.model.ubl.commonaggregatecomponents.PartyType
[ERROR] /home/gadm/workspace/identity-service/identity-service/src/main/java/eu/nimble/core/infrastructure/identity/utils/UblAdapter.java:[151,21] cannot find symbol
  symbol:   method setName(java.lang.String)
  location: variable companyParty of type eu.nimble.service.model.ubl.commonaggregatecomponents.PartyType
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] utility ............................................ SUCCESS [  5.552 s]
[INFO] ubl-data-model ..................................... SUCCESS [ 12.377 s]
[INFO] Parent Project for Identity Service ................ SUCCESS [  0.015 s]
[INFO] Service for managing identities on the platform. ... FAILURE [ 16.342 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 35.479 s
[INFO] Finished at: 2017-08-20T11:14:52+03:00
[INFO] Final Memory: 79M/150M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project identity-service: Compilation failure: Compilation failure:
[ERROR] /home/gadm/workspace/identity-service/identity-service/src/main/java/eu/nimble/core/infrastructure/identity/utils/UblAdapter.java:[20,35] cannot find symbol
[ERROR] symbol:   method getName()
[ERROR] location: variable partyType of type eu.nimble.service.model.ubl.commonaggregatecomponents.PartyType
[ERROR] /home/gadm/workspace/identity-service/identity-service/src/main/java/eu/nimble/core/infrastructure/identity/utils/UblAdapter.java:[129,48] cannot find symbol
[ERROR] symbol:   method getName()
[ERROR] location: variable company of type eu.nimble.service.model.ubl.commonaggregatecomponents.PartyType
[ERROR] /home/gadm/workspace/identity-service/identity-service/src/main/java/eu/nimble/core/infrastructure/identity/utils/UblAdapter.java:[151,21] cannot find symbol
[ERROR] symbol:   method setName(java.lang.String)
[ERROR] location: variable companyParty of type eu.nimble.service.model.ubl.commonaggregatecomponents.PartyType
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :identity-service

**Comment by jinnerbichler** [comment]
Please update the submodule in `./libs/common`.
